-- =============================================================================
-- VERTEX BUILDERS — PRODUCTION SUPABASE SQL MIGRATION
-- Project URL: https://dsvzbpeqwvovbqgpobxz.supabase.co
-- Table: public.contact_submissions
-- =============================================================================

-- 1. Create table with automatic auto-incrementing ID and UTC timestamp
create table if not exists public.contact_submissions (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email text not null,
    phone text,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Performance indexes
create index if not exists idx_contact_submissions_created_at
    on public.contact_submissions (created_at desc);

create index if not exists idx_contact_submissions_email
    on public.contact_submissions (email);

-- 3. Enable Row Level Security (RLS)
alter table public.contact_submissions enable row level security;

-- 4. Clean up any existing policies to make script safely re-runnable (idempotent)
drop policy if exists "Allow public anonymous submissions" on public.contact_submissions;
drop policy if exists "Allow staff and service role reads" on public.contact_submissions;
drop policy if exists "Allow authenticated full access" on public.contact_submissions;

-- 5. RLS Policy: Allow public anonymous site visitors to insert contact inquiries
create policy "Allow public anonymous submissions"
    on public.contact_submissions
    for insert
    to anon, authenticated, service_role
    with check (true);

-- 6. RLS Policy: Allow authenticated staff / service role to view and manage inquiries
create policy "Allow authenticated full access"
    on public.contact_submissions
    for all
    to authenticated, service_role
    using (true)
    with check (true);

-- 7. Grant standard schema and sequence permissions
grant usage on schema public to anon, authenticated, service_role;
grant all on table public.contact_submissions to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- 8. Quick verification: inspect table structure (returns 0 rows initially)
select id, first_name, last_name, email, phone, message, created_at
from public.contact_submissions
limit 1;
