-- =============================================================================
-- VERTEX BUILDERS — SUPABASE SCHEMA MIGRATION
-- Project: https://dsvzbpeqwvovbqgpobxz.supabase.co
-- =============================================================================

-- Create the contact_submissions table
create table if not exists public.contact_submissions (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email text not null,
    phone text,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.contact_submissions enable row level security;

-- Policy 1: Allow public visitors (anon key) to insert inquiries
create policy "Allow public anonymous submissions"
    on public.contact_submissions
    for insert
    to anon
    with check (true);

-- Policy 2: Allow authenticated dashboard staff and service role to read inquiries
create policy "Allow staff and service role reads"
    on public.contact_submissions
    for select
    to authenticated
    using (true);
